# Generated by Django 4.1 on 2022-08-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneno',
            field=models.IntegerField(default=11111),
        ),
    ]
