# Generated by Django 4.1 on 2022-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='op4_count',
            field=models.IntegerField(default=0),
        ),
    ]
